pipeline {
    agent any
    environment {
        // Define your environment variables here
        CREDENTIALS_ID = '82740044-f5e9-4f3c-a093-c1e6eff0b7c6'
        PROJECT_ID = 'sofe3980-lab3'
        CLUSTER_NAME = 'sofe3980u'
        LOCATION = 'northamerica-northeast1-b'
        // Ensure MANIFEST_PATH is defined within the environment block
        MANIFEST_PATH = './BinaryCalculatorWebapp/deployment.yaml'
    }
    tools {
        // Specify any tools needed, like Maven
        maven 'maven'
    }
    stages {
        stage ('Init') {
            steps {
                echo "Start of Job"
                sh 'ls -la'
            }
        }
        stage ('Test') {
            steps {
                sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
            }
        }
        stage ('Build') {
            steps {
                sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
            }
        }
        stage ('Debug Kubectl') {
            steps {
                // Assuming kubectl is available or using the Kubernetes CLI Plugin for Jenkins
                script {
                    // Use the Kubernetes CLI Plugin to configure kubectl
                    withKubeConfig(credentialsId: CREDENTIALS_ID) {
                        sh 'kubectl version || true'
                        sh 'kubectl get nodes || true'
                        sh 'kubectl get svc || true'
                    }
                }
            }
        }
        stage ('Deploy to GKE') {
            steps {
                script {
                    withKubeConfig(credentialsId: CREDENTIALS_ID) {
                        // Use the sh step to apply your Kubernetes manifest
                        sh "kubectl apply -f ${env.MANIFEST_PATH}"
                    }
                }
            }
        }
    }
}
