pipeline {
  agent any
  environment {
    CREDENTIALS_ID = '82740044-f5e9-4f3c-a093-c1e6eff0b7c6'
    PROJECT_ID = 'sofe3980-lab3'
    CLUSTER_NAME = 'sofe3980u'
    CLUSTER_ZONE = 'northamerica-northeast1-b'
    MANIFEST_PATTERN = './BinaryCalculatorWebapp/deployment.yaml'
  }
  tools {
    maven 'maven'
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('Deploy') {
      steps {
        script {
          googleKubernetesEngine(
            credentialsId: "${CREDENTIALS_ID}",
            projectId: "${PROJECT_ID}",
            clusterName: "${CLUSTER_NAME}",
            clusterZone: "${CLUSTER_ZONE}",
            manifestPattern: "${MANIFEST_PATTERN}",
            namespace: 'default',
            verifyDeployments: true
          )
        }
      }
    }
  }
}
